export const SMALL_USER_DEVICE_WIDTH = 450;
export const MEDIUM_USER_DEVICE_WIDTH = 800;
export const SMALL_PROJECT_WINDOW_WIDTH = 350;
export const MEDIUM_PROJECT_WINDOW_WIDTH = 700;
export const LARGE_PROJECT_WINDOW_WIDTH = 800;
export const DOUBLE_CLICK_TIME_OUT = 200;
